// ROUTES
const ABOUT_ROUTE = "/about";
const CONTACT_ROUTE = "/contacts";
const PORTFOLIO_ROUTE = "/portfolio";

// BREAKPOINTS
const MOBILE_BREAKPOINT = import.meta.env.VITE_MOBILE_BREAKPOINT;
const TABLET_BREAKPOINT = import.meta.env.VITE_TABLET_BREAKPOINT;
const DESKTOP_BREAKPOINT = import.meta.env.VITE_DESKTOP_BREAKPOINT;

export {
  ABOUT_ROUTE,
  CONTACT_ROUTE,
  PORTFOLIO_ROUTE,
  MOBILE_BREAKPOINT,
  TABLET_BREAKPOINT,
  DESKTOP_BREAKPOINT,
};
